spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/commit
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
  jwt:
    secret: o2eh1qu7yo978u2q1o7hyua2r7uyr2q9yi7commit
    token:
      access-expiration-time: 3600000
      refresh-expiration-time: 86400000
kakao:
  client_id: 6aa6c76e0fecd5392cf38fb54fcf72b8
  redirect_uri: http://localhost:8080/callback
